name = "PrecisionSpec-Analyzer"
version = "0.1.0"
license = "license"
author = "Mikhail Razumovskiy"
maintainer = "mrazumovskyy@gmail.com"
copyright = "Copyright 2024, Mikhail Razumovskiy"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

